language: java
jdk:
  - oraclejdk11

install: true

script:
  - ./mvn clean install
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.m2

#after_success:
#  - mvn clean test jacoco:report coveralls:report
