
### Spark  Configs -----------------------------------------------------------------------------------
#hadoop home directory  where the winutils.exe binaryry is located -----------------------------------
hadoop.home.dir  : M:/Documents/Misc/forex_clear/resources
spark.serializer : org.apache.spark.serializer.KryoSerializer

### Trade Service Configs ----------------------------------------------------------------------------
#contains trade files     ----------------------------------------------------------------------------
trade.dir : D:/Mkt/MT1

#contains market data files---------------------------------------------------------------------------
market.dir : D:/Mkt/MT1

#contains scenario files------------------------------------------------------------------------------
scenario.dir : D:/Mkt/MT1

#location of working directory------------------------------------------------------------------------
working.dir : M:/Documents/Misc/working

#results will be saved in this directory--------------------------------------------------------------
result.dir : results



